/*
 * Copyright 2022-2023 NXP.
 * NXP Confidential. This software is owned or controlled by NXP and may only be used strictly in accordance
 * with the license terms that accompany it. By expressly accepting such terms or by downloading, installing,
 * activating and/or otherwise using the software, you are agreeing that you have read, and that you
 * agree to comply with and are bound by, such license terms. If you do not agree to be bound by the
 * applicable license terms, then you may not retain, install, activate or otherwise use the software.
 */

#ifndef _SLN_FLASH_FILES_H_
#define _SLN_FLASH_FILES_H_

/* Used to include app specific files */

/* Authentication certificates.*/
#define ROOT_CA_CERT       "ca_root.dat"
#define APP_A_SIGNING_CERT "app_a_sign_cert.dat"
#define APP_B_SIGNING_CERT "app_b_sign_cert.dat"
#define CRED_SIGNING_CERT  "cred_sign_cert.dat"

/* Certificate to connect to the amazon mqtt broker */
#define clientcredentialCLIENT_CERTIFICATE_PEM "cert.dat"

/* Private key used for encryption for TLS */
#define clientcredentialCLIENT_PRIVATE_KEY_PEM "pkey.dat"

/* Audio files */
#define AUDIO_WW_DETECTED                                        "Additional_Prompts/Common/ww_detected.opus"
#define AUDIO_TONE_TIMEOUT                                       "Additional_Prompts/Common/tone_timeout.opus"
#define AUDIO_DEMO_NAME_TEST_CN                                  "Additional_Prompts/CN/demo_name_test_cn.opus"
#define AUDIO_ELEVATOR_DEMO_CN                                   "Additional_Prompts/CN/elevator_demo_cn.opus"
#define AUDIO_ELEVATOR_MULTILINGUAL_CN                           "Additional_Prompts/CN/elevator_multilingual_cn.opus"
#define AUDIO_LANGUAGE_TEST_CN                                   "Additional_Prompts/CN/language_test_cn.opus"
#define AUDIO_OK_CN                                              "Additional_Prompts/CN/ok_cn.opus"
#define AUDIO_SMART_HOME_DEMO_CN                                 "Additional_Prompts/CN/smart_home_demo_cn.opus"
#define AUDIO_SMART_HOME_MULTILINGUAL_CN                         "Additional_Prompts/CN/smart_home_multilingual_cn.opus"
#define AUDIO_WASHING_MACHINE_DEMO_CN                            "Additional_Prompts/CN/washing_machine_demo_cn.opus"
#define AUDIO_WASHING_MACHINE_MULTILINGUAL_CN                    "Additional_Prompts/CN/washing_machine_multilingual_cn.opus"
#define AUDIO_DEMO_NAME_TEST_DE                                  "Additional_Prompts/DE/demo_name_test_de.opus"
#define AUDIO_ELEVATOR_DEMO_DE                                   "Additional_Prompts/DE/elevator_demo_de.opus"
#define AUDIO_ELEVATOR_MULTILINGUAL_DE                           "Additional_Prompts/DE/elevator_multilingual_de.opus"
#define AUDIO_LANGUAGE_TEST_DE                                   "Additional_Prompts/DE/language_test_de.opus"
#define AUDIO_OK_DE                                              "Additional_Prompts/DE/ok_de.opus"
#define AUDIO_SMART_HOME_DEMO_DE                                 "Additional_Prompts/DE/smart_home_demo_de.opus"
#define AUDIO_SMART_HOME_MULTILINGUAL_DE                         "Additional_Prompts/DE/smart_home_multilingual_de.opus"
#define AUDIO_WASHING_MACHINE_DEMO_DE                            "Additional_Prompts/DE/washing_machine_demo_de.opus"
#define AUDIO_WASHING_MACHINE_MULTILINGUAL_DE                    "Additional_Prompts/DE/washing_machine_multilingual_de.opus"
#define AUDIO_DEMO_NAME_TEST_EN                                  "Additional_Prompts/EN/demo_name_test_en.opus"
#define AUDIO_ELEVATOR_DEMO_EN                                   "Additional_Prompts/EN/elevator_demo_en.opus"
#define AUDIO_ELEVATOR_MULTILINGUAL_EN                           "Additional_Prompts/EN/elevator_multilingual_en.opus"
#define AUDIO_LANGUAGE_TEST_EN                                   "Additional_Prompts/EN/language_test_en.opus"
#define AUDIO_OK_EN                                              "Additional_Prompts/EN/ok_en.opus"
#define AUDIO_SMART_HOME_DEMO_EN                                 "Additional_Prompts/EN/smart_home_demo_en.opus"
#define AUDIO_SMART_HOME_MULTILINGUAL_EN                         "Additional_Prompts/EN/smart_home_multilingual_en.opus"
#define AUDIO_WASHING_MACHINE_DEMO_EN                            "Additional_Prompts/EN/washing_machine_demo_en.opus"
#define AUDIO_WASHING_MACHINE_MULTILINGUAL_EN                    "Additional_Prompts/EN/washing_machine_multilingual_en.opus"
#define AUDIO_DEMO_NAME_TEST_FR                                  "Additional_Prompts/FR/demo_name_test_fr.opus"
#define AUDIO_ELEVATOR_DEMO_FR                                   "Additional_Prompts/FR/elevator_demo_fr.opus"
#define AUDIO_ELEVATOR_MULTILINGUAL_FR                           "Additional_Prompts/FR/elevator_multilingual_fr.opus"
#define AUDIO_LANGUAGE_TEST_FR                                   "Additional_Prompts/FR/language_test_fr.opus"
#define AUDIO_OK_FR                                              "Additional_Prompts/FR/ok_fr.opus"
#define AUDIO_SMART_HOME_DEMO_FR                                 "Additional_Prompts/FR/smart_home_demo_fr.opus"
#define AUDIO_SMART_HOME_MULTILINGUAL_FR                         "Additional_Prompts/FR/smart_home_multilingual_fr.opus"
#define AUDIO_WASHING_MACHINE_DEMO_FR                            "Additional_Prompts/FR/washing_machine_demo_fr.opus"
#define AUDIO_WASHING_MACHINE_MULTILINGUAL_FR                    "Additional_Prompts/FR/washing_machine_multilingual_fr.opus"
#define AUDIO_FIRST_FLOOR_CN                                     "Elevator/CN/01_first_floor_cn.opus"
#define AUDIO_SECOND_FLOOR_CN                                    "Elevator/CN/02_second_floor_cn.opus"
#define AUDIO_THIRD_FLOOR_CN                                     "Elevator/CN/03_third_floor_cn.opus"
#define AUDIO_FOURTH_FLOOR_CN                                    "Elevator/CN/04_fourth_floor_cn.opus"
#define AUDIO_FIFTH_FLOOR_CN                                     "Elevator/CN/05_fifth_floor_cn.opus"
#define AUDIO_MAIN_LOBBY_CN                                      "Elevator/CN/06_main_lobby_cn.opus"
#define AUDIO_GROUND_FLOOR_CN                                    "Elevator/CN/07_ground_floor_cn.opus"
#define AUDIO_BASEMENT_FLOOR_CN                                  "Elevator/CN/08_basement_floor_cn.opus"
#define AUDIO_OPEN_DOOR_CN                                       "Elevator/CN/09_open_door_cn.opus"
#define AUDIO_CLOSE_DOOR_CN                                      "Elevator/CN/10_close_door_cn.opus"
#define AUDIO_FIRST_FLOOR_DE                                     "Elevator/DE/01_first_floor_de.opus"
#define AUDIO_SECOND_FLOOR_DE                                    "Elevator/DE/02_second_floor_de.opus"
#define AUDIO_THIRD_FLOOR_DE                                     "Elevator/DE/03_third_floor_de.opus"
#define AUDIO_FOURTH_FLOOR_DE                                    "Elevator/DE/04_fourth_floor_de.opus"
#define AUDIO_FIFTH_FLOOR_DE                                     "Elevator/DE/05_fifth_floor_de.opus"
#define AUDIO_MAIN_LOBBY_DE                                      "Elevator/DE/06_main_lobby_de.opus"
#define AUDIO_GROUND_FLOOR_DE                                    "Elevator/DE/07_ground_floor_de.opus"
#define AUDIO_BASEMENT_FLOOR_DE                                  "Elevator/DE/08_basement_floor_de.opus"
#define AUDIO_OPEN_DOOR_DE                                       "Elevator/DE/09_open_door_de.opus"
#define AUDIO_CLOSE_DOOR_DE                                      "Elevator/DE/10_close_door_de.opus"
#define AUDIO_FIRST_FLOOR_EN                                     "Elevator/EN/01_first_floor_en.opus"
#define AUDIO_SECOND_FLOOR_EN                                    "Elevator/EN/02_second_floor_en.opus"
#define AUDIO_THIRD_FLOOR_EN                                     "Elevator/EN/03_third_floor_en.opus"
#define AUDIO_FOURTH_FLOOR_EN                                    "Elevator/EN/04_fourth_floor_en.opus"
#define AUDIO_FIFTH_FLOOR_EN                                     "Elevator/EN/05_fifth_floor_en.opus"
#define AUDIO_MAIN_LOBBY_EN                                      "Elevator/EN/06_main_lobby_en.opus"
#define AUDIO_GROUND_FLOOR_EN                                    "Elevator/EN/07_ground_floor_en.opus"
#define AUDIO_BASEMENT_FLOOR_EN                                  "Elevator/EN/08_basement_floor_en.opus"
#define AUDIO_OPEN_DOOR_EN                                       "Elevator/EN/09_open_door_en.opus"
#define AUDIO_CLOSE_DOOR_EN                                      "Elevator/EN/10_close_door_en.opus"
#define AUDIO_FIRST_FLOOR_FR                                     "Elevator/FR/01_first_floor_fr.opus"
#define AUDIO_SECOND_FLOOR_FR                                    "Elevator/FR/02_second_floor_fr.opus"
#define AUDIO_THIRD_FLOOR_FR                                     "Elevator/FR/03_third_floor_fr.opus"
#define AUDIO_FOURTH_FLOOR_FR                                    "Elevator/FR/04_fourth_floor_fr.opus"
#define AUDIO_FIFTH_FLOOR_FR                                     "Elevator/FR/05_fifth_floor_fr.opus"
#define AUDIO_MAIN_LOBBY_FR                                      "Elevator/FR/06_main_lobby_fr.opus"
#define AUDIO_GROUND_FLOOR_FR                                    "Elevator/FR/07_ground_floor_fr.opus"
#define AUDIO_BASEMENT_FLOOR_FR                                  "Elevator/FR/08_basement_floor_fr.opus"
#define AUDIO_OPEN_DOOR_FR                                       "Elevator/FR/09_open_door_fr.opus"
#define AUDIO_CLOSE_DOOR_FR                                      "Elevator/FR/10_close_door_fr.opus"
#define AUDIO_TURN_ON_THE_LIGHTS_CN                              "Smart_Home/CN/01_turn_on_the_lights_cn.opus"
#define AUDIO_TURN_OFF_THE_LIGHTS_CN                             "Smart_Home/CN/02_turn_off_the_lights_cn.opus"
#define AUDIO_TEMPERATURE_HIGHER_CN                              "Smart_Home/CN/03_temperature_higher_cn.opus"
#define AUDIO_TEMPERATURE_LOWER_CN                               "Smart_Home/CN/04_temperature_lower_cn.opus"
#define AUDIO_OPEN_THE_WINDOW_CN                                 "Smart_Home/CN/05_open_the_window_cn.opus"
#define AUDIO_CLOSE_THE_WINDOW_CN                                "Smart_Home/CN/06_close_the_window_cn.opus"
#define AUDIO_MAKE_IT_BRIGHTER_CN                                "Smart_Home/CN/07_make_it_brighter_cn.opus"
#define AUDIO_MAKE_IT_DARKER_CN                                  "Smart_Home/CN/08_make_it_darker_cn.opus"
#define AUDIO_TURN_ON_THE_LIGHTS_DE                              "Smart_Home/DE/01_turn_on_the_lights_de.opus"
#define AUDIO_TURN_OFF_THE_LIGHTS_DE                             "Smart_Home/DE/02_turn_off_the_lights_de.opus"
#define AUDIO_TEMPERATURE_HIGHER_DE                              "Smart_Home/DE/03_temperature_higher_de.opus"
#define AUDIO_TEMPERATURE_LOWER_DE                               "Smart_Home/DE/04_temperature_lower_de.opus"
#define AUDIO_OPEN_THE_WINDOW_DE                                 "Smart_Home/DE/05_open_the_window_de.opus"
#define AUDIO_CLOSE_THE_WINDOW_DE                                "Smart_Home/DE/06_close_the_window_de.opus"
#define AUDIO_MAKE_IT_BRIGHTER_DE                                "Smart_Home/DE/07_make_it_brighter_de.opus"
#define AUDIO_MAKE_IT_DARKER_DE                                  "Smart_Home/DE/08_make_it_darker_de.opus"
#define AUDIO_TURN_ON_THE_LIGHTS_EN                              "Smart_Home/EN/01_turn_on_the_lights_en.opus"
#define AUDIO_TURN_OFF_THE_LIGHTS_EN                             "Smart_Home/EN/02_turn_off_the_lights_en.opus"
#define AUDIO_TEMPERATURE_HIGHER_EN                              "Smart_Home/EN/03_temperature_higher_en.opus"
#define AUDIO_TEMPERATURE_LOWER_EN                               "Smart_Home/EN/04_temperature_lower_en.opus"
#define AUDIO_OPEN_THE_WINDOW_EN                                 "Smart_Home/EN/05_open_the_window_en.opus"
#define AUDIO_CLOSE_THE_WINDOW_EN                                "Smart_Home/EN/06_close_the_window_en.opus"
#define AUDIO_MAKE_IT_BRIGHTER_EN                                "Smart_Home/EN/07_make_it_brighter_en.opus"
#define AUDIO_MAKE_IT_DARKER_EN                                  "Smart_Home/EN/08_make_it_darker_en.opus"
#define AUDIO_TURN_ON_THE_LIGHTS_FR                              "Smart_Home/FR/01_turn_on_the_lights_fr.opus"
#define AUDIO_TURN_OFF_THE_LIGHTS_FR                             "Smart_Home/FR/02_turn_off_the_lights_fr.opus"
#define AUDIO_TEMPERATURE_HIGHER_FR                              "Smart_Home/FR/03_temperature_higher_fr.opus"
#define AUDIO_TEMPERATURE_LOWER_FR                               "Smart_Home/FR/04_temperature_lower_fr.opus"
#define AUDIO_OPEN_THE_WINDOW_FR                                 "Smart_Home/FR/05_open_the_window_fr.opus"
#define AUDIO_CLOSE_THE_WINDOW_FR                                "Smart_Home/FR/06_close_the_window_fr.opus"
#define AUDIO_MAKE_IT_BRIGHTER_FR                                "Smart_Home/FR/07_make_it_brighter_fr.opus"
#define AUDIO_MAKE_IT_DARKER_FR                                  "Smart_Home/FR/08_make_it_darker_fr.opus"
#define AUDIO_DELICATE_CN                                        "Washing_Machine/CN/01_delicate_cn.opus"
#define AUDIO_NORMAL_CN                                          "Washing_Machine/CN/02_normal_cn.opus"
#define AUDIO_HEAVY_DUTY_CN                                      "Washing_Machine/CN/03_heavy_duty_cn.opus"
#define AUDIO_WHITES_CN                                          "Washing_Machine/CN/04_whites_cn.opus"
#define AUDIO_START_CN                                           "Washing_Machine/CN/05_start_cn.opus"
#define AUDIO_CANCEL_CN                                          "Washing_Machine/CN/06_cancel_cn.opus"
#define AUDIO_DELICATE_DE                                        "Washing_Machine/DE/01_delicate_de.opus"
#define AUDIO_NORMAL_DE                                          "Washing_Machine/DE/02_normal_de.opus"
#define AUDIO_HEAVY_DUTY_DE                                      "Washing_Machine/DE/03_heavy_duty_de.opus"
#define AUDIO_WHITES_DE                                          "Washing_Machine/DE/04_whites_de.opus"
#define AUDIO_START_DE                                           "Washing_Machine/DE/05_start_de.opus"
#define AUDIO_CANCEL_DE                                          "Washing_Machine/DE/06_cancel_de.opus"
#define AUDIO_DELICATE_EN                                        "Washing_Machine/EN/01_delicate_en.opus"
#define AUDIO_NORMAL_EN                                          "Washing_Machine/EN/02_normal_en.opus"
#define AUDIO_HEAVY_DUTY_EN                                      "Washing_Machine/EN/03_heavy_duty_en.opus"
#define AUDIO_WHITES_EN                                          "Washing_Machine/EN/04_whites_en.opus"
#define AUDIO_START_EN                                           "Washing_Machine/EN/05_start_en.opus"
#define AUDIO_CANCEL_EN                                          "Washing_Machine/EN/06_cancel_en.opus"
#define AUDIO_DELICATE_FR                                        "Washing_Machine/FR/01_delicate_fr.opus"
#define AUDIO_NORMAL_FR                                          "Washing_Machine/FR/02_normal_fr.opus"
#define AUDIO_HEAVY_DUTY_FR                                      "Washing_Machine/FR/03_heavy_duty_fr.opus"
#define AUDIO_WHITES_FR                                          "Washing_Machine/FR/04_whites_fr.opus"
#define AUDIO_START_FR                                           "Washing_Machine/FR/05_start_fr.opus"
#define AUDIO_CANCEL_FR                                          "Washing_Machine/FR/06_cancel_fr.opus"
#endif /* _SLN_FLASH_FILES_H_ */
